# Site settings
title: NZ CPL Training Blog
email: pete.russell01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Study notes for New Zealand CPL flight training.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nzcpl.peterussell.me" # the base hostname & protocol for your site
twitter_username: nz_pete
github_username:  peterussell
instagram_username: raybansandabigwatch

# Build settings
markdown: kramdown

paginate: 4

author: Pete Russell

gems: [jekyll-paginate]
